# This is a basic workflow to help you get started with Actions

name: Github Actions

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
  
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v2
  
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
  
      - name: Build with Maven
        run: mvn -B package --file pom.xml
  
      - name: Docker build
        run: |
          docker login --username="$dockername" --password="$dockerpass"
          docker build -t hjkwon0814/docker-repo:second .
          docker push hjkwon0814/docker-repo:second
        env:
          dockername: ${{secrets.DOCKERHUB_USERNAME}}
          dockerpass: ${{secrets.DOCKERHUB_TOKEN}}
          
#   deploy:
#     needs: build  # build 후에 실행되도록 정의
#     name: Deploy
#     runs-on: [ self-hosted, label-go ] # AWS ./configure에서 사용할 label명
#     steps:
#       - name: Login to ghcr
#         uses: docker/login-action@v1
#         with:
#          registry: ghcr.io
#          username: ${{ github.actor }}
#          password: ${{ secrets.GHCR_TOKEN }}
        
#       - name: Docker run
#         run: |
#          docker stop myserver && docker rm myserver && docker rmi hjkwon0814/docker-repo:second
#          docker run -d -p 8080:8080 --name myserver -v mannayo-vol:/home/ec2-user/images --restart always hjkwon0814/docker-repo:second


# jobs:
#   push_to_registry:
#     name: Push Docker image to Docker Hub
#     runs-on: ubuntu-latest
#     steps:
#       - name: Check out the repo
#         uses: actions/checkout@v3
      
#       - name: Log in to Docker Hub
#         uses: docker/login-action@v2
#         with:
#           username: hjkwon0814
#           password: 254a0e24-a567-4538-a42e-8b962f5b6956
      
#       - name: Extract metadata (tags, labels) for Docker
#         id: meta
#         uses: docker/metadata-action@v2
#         with:
#           images: hjkwon0814/spring-cicd
      
#       - name: Build and push Docker image
#         uses: docker/build-push-action@v2
#         with:
#           context: .
#           push: true
#           tags: ${{ steps.meta.outputs.tags }}
#           labels: ${{ steps.meta.outputs.labels }}
          

